MODEL:
  TYPE: generalized_rcnn
  CONV_BODY: ResNet.ResNet50_conv4_body
  FASTER_RCNN: True
  MASK_ON: False  # True
RESNETS:
  IMAGENET_PRETRAINED_WEIGHTS: 'data/pretrained_model/resnet50_caffe.pth'
NUM_GPUS: 8
SOLVER:
  WEIGHT_DECAY: 0.0001
  LR_POLICY: steps_with_decay
  BASE_LR: 0.01 # 0.01
  GAMMA: 0.1
  # 1x schedule (note TRAIN.IMS_PER_BATCH: 1)
  MAX_ITER: 24000
  STEPS: [0, 15000, 19000]
  # gk_yy 10500 8250 9000 最好节点
  # all_yy 13500 6750 10500#
RPN:
  SIZES: (16, 32, 64, 128, 256, 512)
FAST_RCNN:
  ROI_BOX_HEAD: ResNet.ResNet_roi_conv5_head
  ROI_XFORM_METHOD: RoIAlign # RoIPoolF RoIAlign
  USE_CLS_WEIGHT: True  # LJY
MRCNN:
  ROI_MASK_HEAD: mask_rcnn_heads.mask_rcnn_fcn_head_v0upshare
  RESOLUTION: 14
  ROI_XFORM_METHOD: RoIAlign
  ROI_XFORM_RESOLUTION: 14
  DILATION: 1  # default 2
  CONV_INIT: MSRAFill  # default: GaussianFill
TRAIN:
  # SCALES: (1400, 1500, 1600, 1700, 1800, 1900, 2000)
  SCALES: (800, 900, 1000, 1100, 1200, 1300, 1400)
  MAX_SIZE: 1600
  IMS_PER_BATCH: 1
  BATCH_SIZE_PER_IM: 512 # 512
  USE_FLIPPED: True # True
  # RPN_PRE_NMS_TOP_N: 2000  # Per FPN level
  # RPN_POSITIVE_OVERLAP: 0.5
  # RPN_NEGATIVE_OVERLAP: 0.2
TEST:
  BBOX_AUG:
      ENABLED: False
      SCALES: (800, 1100, 1400)
      H_FLIP: False
      MAX_SIZE: 1600
  SCALE: 1200 # 1000
  MAX_SIZE: 1600
  NMS: 0.01 # 0.01
  RPN_PRE_NMS_TOP_N: 6000 # 6000
  RPN_POST_NMS_TOP_N: 1000 # 1000

DROP_NEGATIVE_IMAGES: False  # LJY
HISTO_EQUAL: False  # LJY

# False True
#USE_CLS_RELA: True
#USE_SPA_RELA: True
#USE_CONTEXT_RELA: True
# USE_INNER_CONTEXT_RELA: False
USE_CASCADE: True
USE_DCN: True
