MODEL:
  TYPE: generalized_rcnn
  CONV_BODY: ResNet.ResNet50_conv4_body
  FASTER_RCNN: True
NUM_GPUS: 8
RESNETS:
  IMAGENET_PRETRAINED_WEIGHTS: 'data/pretrained_model/resnet50_caffe.pth'
SOLVER:
  WEIGHT_DECAY: 0.0001
  LR_POLICY: steps_with_decay
  BASE_LR: 0.01
  GAMMA: 0.1
  # 1x schedule (note TRAIN.IMS_PER_BATCH: 1)
  MAX_ITER: 96000
  STEPS: [0, 60000, 80000]
RPN:
  SIZES: (16, 32, 64, 128, 256, 512)
  CLS_ACTIVATION: 'softmax'
  LOSS: 'focal'
FAST_RCNN:
  ROI_BOX_HEAD: ResNet.ResNet_roi_conv5_head
  ROI_XFORM_METHOD: RoIAlign
TRAIN:
  SCALES: (800, 1000, 1200, 1400)
  MAX_SIZE: 1600
  IMS_PER_BATCH: 1
  BATCH_SIZE_PER_IM: 512
  USE_FLIPPED: True
  RPN_BATCH_SIZE_PER_IM: 1000000
  RPN_POSITIVE_OVERLAP: 0.7
  RPN_NEGATIVE_OVERLAP: 0.3
TEST:
#  BBOX_AUG:
#    CROP4: True
#    ENABLED: True
#    SCALES: (1000, 1400)
#    MAX_SIZE: 2000
#    SCORE_HEUR: 'UNION'
#    COORD_HEUR: 'UNION'
  SCALE: 1200
  MAX_SIZE: 1600
  NMS: 0.01
  RPN_PRE_NMS_TOP_N: 6000
  RPN_POST_NMS_TOP_N: 1000
