MODEL:
  TYPE: generalized_rcnn
  CONV_BODY: FPN.fpn_ResNet50_conv5_body
  FASTER_RCNN: True
RESNETS:
  IMAGENET_PRETRAINED_WEIGHTS: 'data/pretrained_model/resnet50_caffe.pth'
NUM_GPUS: 8
SOLVER:
  WEIGHT_DECAY: 0.0001
  LR_POLICY: steps_with_decay
  BASE_LR: 0.02
  GAMMA: 0.1
  MAX_ITER: 10500
  STEPS: [0, 5000, 7500]
FPN:
  FPN_ON: True
  MULTILEVEL_ROIS: True
  MULTILEVEL_RPN: True
  RPN_ANCHOR_START_SIZE: 16
FAST_RCNN:
  ROI_BOX_HEAD: fast_rcnn_heads.roi_2mlp_head
  ROI_XFORM_METHOD: RoIAlign
  ROI_XFORM_RESOLUTION: 7
  ROI_XFORM_SAMPLING_RATIO: 2
  USE_CLS_WEIGHT: True  # LJY
TRAIN:
  SCALES: (800, 1000, 1200, 1400)
  MAX_SIZE: 1600
  IMS_PER_BATCH: 1
  RPN_BATCH_SIZE_PER_IM: 128
  BATCH_SIZE_PER_IM: 128
  USE_FLIPPED: True
  RPN_PRE_NMS_TOP_N: 2000  # Per FPN level
TEST:
  SCALE: 1200
  MAX_SIZE: 1600
  NMS: 0.5 #论文里都是0.5测试
  RPN_PRE_NMS_TOP_N: 1000  # Per FPN level
  RPN_POST_NMS_TOP_N: 1000