MODEL:
  TYPE: generalized_rcnn
  CONV_BODY: ResNet.ResNet50_conv5_body
  FASTER_RCNN: False
NUM_GPUS: 8
RESNETS:
  IMAGENET_PRETRAINED_WEIGHTS: 'data/pretrained_model/resnet50_caffe.pth'
SOLVER:
  WEIGHT_DECAY: 0.0001
  LR_POLICY: steps_with_decay
  BASE_LR: 0.01
  GAMMA: 0.1
  # 1x schedule (note TRAIN.IMS_PER_BATCH: 1)
  MAX_ITER: 3000
  STEPS: [0, 1000, 2000]
RPN:
  SIZES: (16, 32, 64, 128, 256, 512)
FAST_RCNN:
  ROI_BOX_HEAD: fast_rcnn_heads.roi_2mlp_head
  ROI_XFORM_METHOD: RoIAlign
  USE_CLS_WEIGHT: False  # LJY
  ROI_XFORM_RESOLUTION: 7
TRAIN:
  SCALES: (1200, )
  MAX_SIZE: 1600
  IMS_PER_BATCH: 1
  RPN_BATCH_SIZE_PER_IM: 256
  BATCH_SIZE_PER_IM: 512
  USE_FLIPPED: False
  RPN_POSITIVE_OVERLAP: 0.7
  USE_REGRESSION: False  # LJY
  SNAPSHOT_ITERS: 1000
TEST:
  SCALE: 1200
  MAX_SIZE: 1600
  NMS: 0.01
  RPN_PRE_NMS_TOP_N: 6000
  RPN_POST_NMS_TOP_N: 1000
  SCORE_THRESH: 0.02  # default: 0.02

DROP_NEGATIVE_IMAGES: False # LJY
HISTO_EQUAL: False  # LJY
